### ISSUE TITLE
Create more weapons and more armmors and more shields

### ISSUE THREAD

**Issue by EnterVPL** [EnterVPL/FoxSymulator#44]

**Comment by Yrdenn** [comment]
- [ ] test

**Comment by Yrdenn** [comment]
- [x] **Wooden Set** 

> - [x] Wepon `+1str`
> - [x] Armmor `+1def`
> - [x] Shield `+1def`

- [x] **Iron Set**
> - [x] Wepon `+2str`
> - [x] Armmor `+2def`
> - [x] Shield `+2def`


- [x] **Mitrhril Set**
> - [x] Wepon `+4str`
> - [x] Armmor `+3def, +1str`
> - [x] Shield `+3def, +1str`

- [x] **Crystal Set**
> - [x] Wepon `+3str, +1def`
> - [x] Armmor `+4def`
> - [x] Shield `+4def`

- [x] **Energy Set**
> - [x] Wepon `+3str +1speed`
> - [x] Armmor `+3def +1speed`
> - [x] Shield `+3def +1speed`
